---

- name: Create namespace "{{ prometheus.namespace }}"
  kubernetes.core.k8s:
    name: "{{ prometheus.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Add prometheus Helm repository
  kubernetes.core.helm_repository:
    name: "prometheus-community"
    url: "https://prometheus-community.github.io/helm-charts"
    state: present

- name: Read CA certificate file
  set_fact:
    ca_cert_file: "{{ lookup('file', cert_path_global) }}"

- name: Deploy CA secret manifests from template file
  kubernetes.core.k8s:
    state: present
    template: 'ca-cert-secret.yaml.j2'
  when: cert_path_global != ''

- name: Deploy prometheus loaded from template (helm)
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus.chart_version }}"
    release_namespace: "{{ prometheus.namespace }}"
    create_namespace: false
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

- name: Deploy IngressRoute from template file
  kubernetes.core.k8s:
    state: present
    template: 'ingressRoute.yaml.j2'

