- name: Copying kubeconfig from server
  ansible.builtin.fetch:
    src: "{{ ansible_user_dir }}/.kube/config"
    dest: "~/.kube/config.{{ cluster_name }}"
    flat: true

- name: Modify kubeconfig files locally
  block:
  - name: Replace "default" cluster name with "{{ cluster_name }}"
    ansible.builtin.replace:
      path: ~/.kube/config.{{ cluster_name }}
      regexp: '\bdefault\b'
      replace: '{{ cluster_name }}'
      backup: yes

  - name: Backup original kubeconfig
    ansible.builtin.copy:
      src: ~/.kube/config
      dest: ~/.kube/config.bak

  - name: Merge configs
    ansible.builtin.shell: >
      KUBECONFIG=~/.kube/config:~/.kube/config.{{ cluster_name }}
      kubectl config view --merge --flatten > ~/.kube/config.merged

  - name: Replace original kubeconfig with merged config
    ansible.builtin.copy:
      src: ~/.kube/config.merged
      dest: ~/.kube/config

  - name: Remove temporary merged kubeconfig
    ansible.builtin.file:
      path: ~/.kube/config.merged
      state: absent
  delegate_to: localhost
  connection: local
