---
k3s_kubectl_binary: k3s kubectl

cilium:
  bgp: false
  exportPodCIDR: true  # noqa var-naming
  bgp_my_asn: 64513
  bgp_peer_asn: 64512
  bgp_neighbors: []
  bgp_neighbors_groups: ['k3s_all']
  bgp_lb_cidr: 192.168.31.0/24
  hubble: true
  mode: native

bpf_lb_algorithm: maglev
bpf_lb_mode: hybrid

cluster_cidr: 10.52.0.0/16
enable_bpf_masquerade: true
kube_proxy_replacement: true

# Name of the master group
group_name_master: k3s_servers

metal_lb_mode: layer2
metal_lb_available_timeout: 240s
metal_lb_controller_tag_version: v0.14.3
metal_lb_ip_range: 192.168.30.80-192.168.30.90
