---

- name: Add longhorn Helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    url: https://charts.longhorn.io
    state: present

- name: Deploy longhorn loaded from template (helm)
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn.chart_version }}"
    release_namespace: "{{ longhorn.namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

- name: Remove default StorageClass local-path.yaml (this is not persistent)
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: StorageClass
    name: local-path

- name: Deploy IngressRoute from template file for longhorn dashboard
  kubernetes.core.k8s:
    state: present
    template: 'dashboard/ingressRoute.yaml.j2'
  when: longhorn.dashboard.enabled
