---

- name: Check if Helm is installed
  hosts: k3s_admin
  connection: local
  gather_facts: false
  tasks:
    - name: Checking Helm version
      ansible.builtin.command: "helm version --client"
      register: helm_version
      failed_when: helm_version.rc != 0 and helm_version.stderr != ""
      changed_when: false

- name: Include Helm install roles
  hosts: k3s_admin
  connection: local
  gather_facts: false
  roles:
    - role: authentik
      when: authentik.enabled
      tags:
        - authentik
    - role: nextcloud
      when: nextcloud.enabled
      tags:
        - nextcloud
    - role: gitlab-runner
      when: gitlab.runner.enabled
      tags:
        - gitlab-runner
    - role: argocd
      when: argocd.enabled
      tags:
        - argocd
    - role: argocd-image-updater
      when: argocd.image_updater.enabled
      tags:
        - argocd-image-updater
    - role: nfs-client
      when: nfs_client.enabled
      tags:
        - nfs-client
    - role: qbittorrent
      when: qbittorrent.enabled
      tags:
        - qbittorrent
    - role: home-assistant
      when: home_assistant.enabled
      tags:
        - home-assistant


