---

- name: Check if Helm is installed
  hosts: k3s_admin
  connection: local
  tasks:
    - name: Checking Helm version
      ansible.builtin.command: "helm version --client"
      register: helm_version
      failed_when: helm_version.rc != 0 and helm_version.stderr != ""
      changed_when: false

- name: Include Helm install roles
  hosts: k3s_admin
  connection: local
  gather_facts: false
  roles:
    - role: cert-manager
      when: cert_manager.enabled
    - role: traefik
      when: traefik.enabled
