---

- name: Prepare Proxmox cluster
  hosts: proxmox
  become: true
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc.enabled

- name: Prepare k3s nodes
  hosts: k3s_cluster
  roles:
    - role: lxc
      become: true
      when: proxmox_lxc.enabled
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true
      when: raspberrypi.enabled
    - role: custom_registries
      become: true
      when: custom_registries.enabled

- name: Setup k3s masters
  hosts: k3s_servers
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s workers
  hosts: k3s_workers
  roles:
    - role: k3s_worker
      become: true

- name: Configure k3s cluster
  hosts: k3s_servers
  roles:
    - role: k3s_server_post
      become: true

- name: Copying kubeconfig file
  hosts: k3s_servers[0]
  roles:
    - role: fetch

- name: Include base ingress helm install after k3s installation
  ansible.builtin.import_playbook: base_ingress.yaml
  tags: ingress

- name: Include base storage helm install after k3s installation
  ansible.builtin.import_playbook: base_storage.yaml
  tags: storage

- name: Include base apps helm install after k3s installation
  ansible.builtin.import_playbook: base_apps.yaml
  tags: apps
