---

- name: Add gitlab Helm repository
  kubernetes.core.helm_repository:
    name: "gitlab"
    url: "https://charts.gitlab.io"
    state: present

- name: Deploy gitlab-runner loaded from template (helm)
  kubernetes.core.helm:
    name: gitlab-runner
    chart_ref: gitlab/gitlab-runner
    chart_version: "{{ gitlab.runner.chart_version }}"
    release_namespace: "{{ gitlab.runner.namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

